// =============================================================================
// sdf-js/src/icons/categories.js — Curated Phosphor icon names per category
// -----------------------------------------------------------------------------
// 8 domain categories of kebab-case Phosphor icon names. Bake script reads
// node_modules/@phosphor-icons/core/assets/regular/<name>.svg for each name.
//
// Full curation lives here; expand by adding names. Names must match
// Phosphor's filename (no extension). To list available: `ls
// node_modules/@phosphor-icons/core/assets/regular/`.
//
// Per docs/superpowers/specs/2026-06-22-atlas-present-sprint-15-design.md §7.
// =============================================================================

export const CATEGORIES = {
  business: [
    // Office & meetings
    'briefcase',
    'briefcase-metal',
    'office-chair',
    'projector-screen',
    'projector-screen-chart',
    'presentation',
    'presentation-chart',
    'handshake',
    'address-book',
    'address-book-tabs',
    'video-conference',
    // Charts & KPIs
    'chart-line',
    'chart-line-down',
    'chart-line-up',
    'chart-bar',
    'chart-bar-horizontal',
    'chart-donut',
    'chart-pie',
    'chart-pie-slice',
    'chart-polar',
    'chart-scatter',
    'gauge',
    'speedometer',
    // Strategy & goals
    'target',
    'trophy',
    'medal',
    'medal-military',
    'flag-banner',
    'flag-banner-fold',
    'flag-pennant',
    'flag-checkered',
    'flag',
    'rocket',
    'rocket-launch',
    'lightbulb',
    'lightbulb-filament',
    'certificate',
    'ranking',
    // Documents & process
    'file',
    'file-text',
    'file-pdf',
    'file-doc',
    'file-xls',
    'file-ppt',
    'file-csv',
    'folder',
    'folder-open',
    'folders',
    'archive',
    'clipboard',
    'clipboard-text',
    'notebook',
    'notepad',
    'note',
    'note-blank',
    'note-pencil',
    'paragraph',
    // Lists & structure
    'list',
    'list-bullets',
    'list-checks',
    'list-dashes',
    'list-numbers',
    'list-plus',
    'list-star',
    // Data & analytics
    'funnel',
    'funnel-simple',
    'funnel-x',
    'funnel-simple-x',
    'sort-ascending',
    'sort-descending',
    'table',
    'layout',
    'tag',
    // Communication
    'megaphone',
    'megaphone-simple',
    'printer',
    'screencast',
    'paperclip',
    // Search & discovery
    'magnifying-glass',
    'magnifying-glass-plus',
    'magnifying-glass-minus',
    // Money & deals
    'money',
    'money-wavy',
    'hand-coins',
    'piggy-bank',
    'invoice',
    // Buildings & locations
    'buildings',
    'building',
    'building-office',
    'building-apartment',
    'city',
    'factory',
    'warehouse',
    'shipping-container',
    'globe',
    'globe-hemisphere-east',
    'globe-hemisphere-west',
    'globe-stand',
    'globe-simple',
    'map-trifold',
    'map-pin',
    'compass',
    'compass-rose',
    // Travel
    'airplane',
    'airplane-takeoff',
    'airplane-landing',
    'airplane-in-flight',
    // Commerce
    'shopping-cart',
    'shopping-cart-simple',
    'shopping-bag',
    'shopping-bag-open',
    'storefront',
    'bag',
    'export',
    'trademark',
    'trademark-registered',
    // Process & workflow
    'flow-arrow',
    'network',
    'seal',
    'seal-check',
    'seal-percent',
    'seal-question',
    'seal-warning',
    'stamp',
    // Linking
    'link',
    'link-simple',
    // People (managers, partners)
    'user',
    'user-plus',
    'user-gear',
    'user-check',
    'user-focus',
    'user-list',
    'user-switch',
    'user-circle',
    'identification-badge',
    'identification-card',
    // Finance objects
    'bank',
    'vault',
    'wallet',
    'coins',
    'coin',
    'credit-card',
    'cash-register',
    'receipt',
    // Maps & locations
    'map-pin-area',
    'map-pin-plus',
    'globe-x',
    'airplane-tilt',
    'compass-tool',
    // More data & lists
    'list-heart',
    'stack',
    'stack-simple',
    'stack-plus',
    'stack-minus',
    // Media & presentations
    'microphone',
    'camera',
    'broadcast',
    // More package/shipping
    'package',
  ],

  finance: [
    // Currency symbols
    'currency-dollar',
    'currency-dollar-simple',
    'currency-eur',
    'currency-gbp',
    'currency-jpy',
    'currency-cny',
    'currency-krw',
    'currency-kzt',
    'currency-ngn',
    'currency-rub',
    'currency-inr',
    'currency-btc',
    'currency-eth',
    'currency-circle-dollar',
    // Charts (finance-flavored)
    'trend-up',
    'trend-down',
    'chart-line',
    'chart-line-up',
    'chart-line-down',
    'chart-bar',
    'chart-bar-horizontal',
    'chart-pie',
    'chart-pie-slice',
    'chart-donut',
    'chart-scatter',
    'chart-polar',
    'gauge',
    'speedometer',
    // Money objects
    'coin',
    'coin-vertical',
    'coins',
    'money',
    'money-wavy',
    'cash-register',
    'wallet',
    'credit-card',
    'bank',
    'piggy-bank',
    'vault',
    // Trading & transfers
    'arrow-fat-up',
    'arrow-fat-down',
    'arrow-fat-line-up',
    'arrow-fat-line-down',
    'caret-up',
    'caret-down',
    'caret-up-down',
    'caret-circle-up',
    'caret-circle-down',
    'percent',
    'receipt',
    'receipt-x',
    'invoice',
    'hand-coins',
    'hand-deposit',
    'hand-withdraw',
    // Security & banking
    'lock',
    'lock-key',
    'lock-key-open',
    'lock-open',
    'lock-simple',
    'lock-laminated',
    'shield',
    'shield-check',
    'shield-warning',
    'shield-checkered',
    'shield-star',
    'shield-plus',
    'shield-slash',
    // Documents & records
    'archive',
    'table',
    'funnel',
    'funnel-simple',
    'sort-ascending',
    'sort-descending',
    // Targets & performance
    'seal-check',
    'seal',
    'stamp',
    // Analytics
    'magnifying-glass',
    'magnifying-glass-plus',
    'magnifying-glass-minus',
    // Commerce & industry
    'building',
    'buildings',
    'globe',
    'globe-hemisphere-east',
    'globe-hemisphere-west',
    'globe-stand',
    'globe-simple',
    'storefront',
    'shopping-cart',
    'shopping-bag',
    // Indicators
    'flag',
    'flag-banner',
    // More globe & nav
    'map-trifold',
    'map-pin',
    'compass',
    'compass-rose',
    // Additional indicators
    'city',
    'factory',
    'warehouse',
    // Lock variants
    'lock-laminated-open',
    'lock-simple-open',
    'shield-chevron',
    // Key
    'key',
    'key-return',
  ],

  tech: [
    // Computing
    'cpu',
    'desktop',
    'desktop-tower',
    'laptop',
    'monitor',
    'monitor-play',
    'keyboard',
    'mouse',
    'mouse-simple',
    'graphics-card',
    // Storage & data
    'database',
    'hard-drive',
    'hard-drives',
    'floppy-disk',
    'floppy-disk-back',
    'memory',
    'usb',
    // Cloud & network
    'cloud',
    'cloud-arrow-up',
    'cloud-arrow-down',
    'cloud-check',
    'cloud-x',
    'cloud-warning',
    'cloud-fog',
    'cloud-lightning',
    'wifi-high',
    'wifi-medium',
    'wifi-low',
    'wifi-none',
    'wifi-x',
    'wifi-slash',
    'broadcast',
    'radio',
    // Cell signal
    'cell-signal-full',
    'cell-signal-high',
    'cell-signal-medium',
    'cell-signal-low',
    'cell-signal-none',
    'cell-signal-slash',
    'cell-signal-x',
    'cell-tower',
    // Code & dev
    'code',
    'code-block',
    'code-simple',
    'terminal',
    'terminal-window',
    'git-branch',
    'git-commit',
    'git-diff',
    'git-fork',
    'git-merge',
    'git-pull-request',
    'github-logo',
    'gitlab-logo',
    'gitlab-logo-simple',
    'binary',
    'function',
    'hash',
    'hash-straight',
    // Dev platforms
    'codepen-logo',
    'codesandbox-logo',
    'webhooks-logo',
    'browser',
    'browsers',
    'app-window',
    'app-store-logo',
    // Security
    'shield',
    'shield-check',
    'shield-warning',
    'shield-slash',
    'shield-star',
    'key',
    'key-return',
    'lock',
    'lock-open',
    'lock-key',
    'fingerprint',
    'fingerprint-simple',
    // Devices
    'device-mobile',
    'device-mobile-camera',
    'device-mobile-speaker',
    'device-tablet',
    'device-tablet-camera',
    'device-tablet-speaker',
    'sim-card',
    'devices',
    'device-rotate',
    // Connectivity
    'bluetooth',
    'bluetooth-connected',
    'bluetooth-slash',
    'bluetooth-x',
    'qr-code',
    'barcode',
    'circuitry',
    // Power & energy
    'power',
    'battery-full',
    'battery-high',
    'battery-medium',
    'battery-low',
    'battery-empty',
    'battery-charging',
    'battery-warning',
    'plug',
    'plugs',
    'plugs-connected',
    'solar-panel',
    // AI & hardware
    'robot',
    'drone',
    'magnet',
    'magnet-straight',
    // Dev tools & debugging
    'bug',
    'bug-beetle',
    'bug-droid',
    'log',
    // Media & display
    'monitor-arrow-up',
    'screencast',
    'television',
    'television-simple',
    'camera',
    'camera-plus',
    'camera-rotate',
    'camera-slash',
    // Signals & waves
    'waveform',
    'waveform-slash',
    'wave-sine',
    'wave-square',
    'wave-triangle',
    'wave-sawtooth',
    'waves',
    // Misc tech
    'printer',
    'swap',
    'network',
    'network-slash',
    'network-x',
    // Search & scan
    'magnifying-glass',
    'magnifying-glass-plus',
    'magnifying-glass-minus',
    'scan',
    // Playlist & stream
    'playlist',
    // More file types
    'file-code',
    'file-lock',
    'file-minus',
    'file-plus',
    // More code symbols
    'brackets-angle',
    'brackets-curly',
    'brackets-round',
    'brackets-square',
    // Lock variants
    'lock-laminated-open',
    'lock-simple-open',
    'shield-chevron',
    // Creative / design tools
    'pencil',
    'pencil-simple',
    'pen',
    'paint-bucket',
    'paint-roller',
    // Package management
    'box-arrow-down',
    'box-arrow-up',
    // Sparkle (AI/LLM metaphor)
    'sparkle',
  ],

  medical: [
    // Core medical tools
    'stethoscope',
    'pill',
    'syringe',
    'first-aid',
    'first-aid-kit',
    'thermometer',
    'thermometer-cold',
    'thermometer-hot',
    'thermometer-simple',
    'bandaids',
    'eyedropper',
    'eyedropper-sample',
    'microscope',
    'test-tube',
    'flask',
    'scan',
    // Heart & vitals
    'heart',
    'heart-straight',
    'heart-break',
    'heart-half',
    'heart-straight-break',
    'heartbeat',
    'pulse',
    // Eyes
    'eye',
    'eye-slash',
    'eye-closed',
    'eyes',
    'eyeglasses',
    // Ears & teeth & bones
    'ear',
    'ear-slash',
    'tooth',
    'bone',
    // Brain & nervous
    'brain',
    // Genetics & biology
    'dna',
    'virus',
    // Protective equipment
    'mask-happy',
    'mask-sad',
    'face-mask',
    // Facilities
    'hospital',
    'ambulance',
    'wheelchair',
    'wheelchair-motion',
    'bed',
    'shower',
    'bathtub',
    'toilet',
    // People & activity
    'baby',
    'baby-carriage',
    'person',
    'person-arms-spread',
    'person-simple',
    'person-simple-run',
    'person-simple-walk',
    'person-simple-bike',
    'person-simple-circle',
    'person-simple-hike',
    'person-simple-swim',
    'person-simple-tai-chi',
    'person-simple-throw',
    'person-simple-ski',
    'person-simple-snowboard',
    // Nature / nutrition
    'plant',
    'drop',
    'drop-half',
    'drop-simple',
    'drop-slash',
    'egg',
    // Mental health
    'scan-smiley',
    'hands-praying',
    'chat',
    // Signals & monitoring
    'waveform',
    'waves',
    // Safety & alerts
    'warning',
    'warning-circle',
    'exclamation-mark',
    // Emergency
    'lifebuoy',
    'fire-extinguisher',
    // Nutrition tracking
    'trend-up',
    'trend-down',
    // Biometrics
    'fingerprint',
    'fingerprint-simple',
    // Well-being
    'hand-heart',
    // Status
    'ruler',
    // Lightning (defibrillator metaphor)
    'lightning-a',
    // Music therapy
    'music-notes-plus',
    'music-notes-simple',
    // Scheduling (medical appointments)
    'calendar',
    'calendar-blank',
    'calendar-dot',
    'calendar-dots',
    'calendar-minus',
    'calendar-star',
    'calendar-x',
    'calendar-heart',
    'calendar-slash',
  ],

  hrm: [
    // User profiles
    'user',
    'user-circle',
    'user-circle-check',
    'user-circle-dashed',
    'user-circle-gear',
    'user-circle-minus',
    'user-circle-plus',
    'user-focus',
    'user-gear',
    'user-list',
    'user-minus',
    'user-plus',
    'user-rectangle',
    'user-sound',
    'user-square',
    'user-switch',
    'user-check',
    // Groups & teams
    'users',
    'users-three',
    'users-four',
    // Education & training
    'graduation-cap',
    'student',
    'chalkboard',
    'chalkboard-simple',
    'chalkboard-teacher',
    'book',
    'book-bookmark',
    'book-open',
    'book-open-text',
    'book-open-user',
    'books',
    'article',
    'newspaper',
    'newspaper-clipping',
    // Identity & access
    'identification-badge',
    'identification-card',
    'address-book',
    'address-book-tabs',
    // Work tools
    'briefcase',
    'briefcase-metal',
    'handshake',
    // Communication
    'chats',
    'chats-circle',
    'chats-teardrop',
    'chat',
    'chat-circle',
    'chat-circle-dots',
    'chat-teardrop',
    'headset',
    'headphones',
    'phone',
    'phone-call',
    'video-conference',
    'envelope',
    'envelope-open',
    'envelope-simple',
    // Recognition & rewards
    'star',
    'star-half',
    'trophy',
    'medal',
    'medal-military',
    'ranking',
    'crown',
    'crown-simple',
    'certificate',
    'seal-check',
    // Scheduling & time
    'calendar',
    'calendar-blank',
    'calendar-check',
    'calendar-plus',
    'calendar-minus',
    'calendar-dots',
    'calendar-star',
    'calendar-x',
    'clock',
    'clock-clockwise',
    'clock-user',
    'clock-afternoon',
    'clock-countdown',
    'clock-counter-clockwise',
    'alarm',
    'timer',
    // Performance & reporting
    'chart-bar',
    'chart-line',
    'chart-bar-horizontal',
    'chart-pie',
    'chart-donut',
    'gauge',
    'speedometer',
    'clipboard-text',
    'notepad',
    'file-text',
    'notebook',
    'list',
    'list-checks',
    'list-bullets',
    'list-dashes',
    'list-numbers',
    'list-plus',
    'list-star',
    'list-heart',
    // Documents & filing
    'folder',
    'folder-open',
    'folders',
    'archive',
    'file',
    'file-pdf',
    'file-doc',
    'file-csv',
    'file-xls',
    'file-ppt',
    'clipboard',
    'note',
    'note-blank',
    'note-pencil',
    // Org structure & workflow
    'network',
    'flow-arrow',
    // Feedback & evaluation
    'thumbs-up',
    'thumbs-down',
    // Search & analysis
    'magnifying-glass',
    'magnifying-glass-plus',
    'magnifying-glass-minus',
    // Buildings & facilities
    'building',
    'buildings',
    'building-office',
    'city',
    // Presentation & training materials
    'megaphone',
    'megaphone-simple',
    'presentation',
    'presentation-chart',
    'projector-screen',
    'projector-screen-chart',
    // People activity
    'person',
    'person-arms-spread',
    'person-simple',
    'person-simple-bike',
    'person-simple-circle',
    'person-simple-hike',
    'person-simple-run',
    'person-simple-ski',
    'person-simple-snowboard',
    'person-simple-swim',
    'person-simple-tai-chi',
    'person-simple-throw',
    'person-simple-walk',
    // Career & trends
    'trend-up',
    'trend-down',
    'rocket',
    'rocket-launch',
    'lightbulb',
    'lightbulb-filament',
    'flag',
    'flag-banner',
    // Misc professional
    'seal',
    'stamp',
    // Bookmarks & links
    'bookmark',
    'bookmarks',
    'bookmark-simple',
  ],

  social: [
    // Chat & messaging
    'chat',
    'chat-centered',
    'chat-centered-dots',
    'chat-centered-text',
    'chat-centered-slash',
    'chat-circle',
    'chat-circle-dots',
    'chat-circle-text',
    'chat-circle-slash',
    'chat-dots',
    'chat-slash',
    'chat-teardrop',
    'chat-teardrop-dots',
    'chat-teardrop-text',
    'chat-teardrop-slash',
    'chat-text',
    'chats',
    'chats-circle',
    'chats-teardrop',
    // Reactions & emotions
    'heart',
    'heart-straight',
    'heart-break',
    'heart-half',
    'heart-straight-break',
    'thumbs-up',
    'thumbs-down',
    'hand-heart',
    'hand-waving',
    'hands-clapping',
    'hands-praying',
    'smiley',
    'smiley-wink',
    'smiley-sad',
    'smiley-angry',
    'smiley-meh',
    'smiley-blank',
    'smiley-melting',
    'smiley-nervous',
    'smiley-sticker',
    'smiley-x-eyes',
    // Sharing & posting
    'share',
    'share-fat',
    'share-network',
    'paper-plane',
    'paper-plane-right',
    'paper-plane-tilt',
    'upload',
    'upload-simple',
    'download',
    'download-simple',
    // Contact
    'at',
    'envelope',
    'envelope-open',
    'envelope-simple',
    'envelope-simple-open',
    'phone',
    'phone-call',
    'phone-incoming',
    'phone-outgoing',
    'phone-disconnect',
    'phone-plus',
    'phone-list',
    // Video & live
    'video-camera',
    'video-camera-slash',
    'camera',
    'camera-plus',
    'microphone',
    'microphone-slash',
    'microphone-stage',
    'television',
    'television-simple',
    // Notifications
    'bell',
    'bell-ringing',
    'bell-simple',
    'bell-simple-ringing',
    'bell-slash',
    'bell-simple-slash',
    'bell-z',
    'bell-simple-z',
    'notification',
    // Social platforms
    'instagram-logo',
    'facebook-logo',
    'twitter-logo',
    'x-logo',
    'linkedin-logo',
    'youtube-logo',
    'whatsapp-logo',
    'tiktok-logo',
    'pinterest-logo',
    'reddit-logo',
    'discord-logo',
    'snapchat-logo',
    'telegram-logo',
    'threads-logo',
    'slack-logo',
    'twitch-logo',
    'spotify-logo',
    'soundcloud-logo',
    'patreon-logo',
    'medium-logo',
    'skype-logo',
    'wechat-logo',
    'behance-logo',
    'dribbble-logo',
    'github-logo',
    'figma-logo',
    'apple-podcasts-logo',
    'google-podcasts-logo',
    // Stars & bookmarks
    'star',
    'star-half',
    'bookmark',
    'bookmark-simple',
    'bookmarks',
    // Media content
    'image',
    'image-square',
    'images',
    'images-square',
    'gif',
    'film-reel',
    'film-slate',
    'film-strip',
    'film-script',
    'music-note',
    'music-notes',
    'music-notes-plus',
    'music-notes-simple',
    'playlist',
    'queue',
    // Misc social
    'gift',
    'quotes',
    'link',
    'link-simple',
    // Articles & content
    'article',
    'newspaper',
    'newspaper-clipping',
    'book-open',
    'books',
    // More hand gestures
    'hand-peace',
    'hand-fist',
    'hand-palm',
    'hand-pointing',
    // More phone states
    'phone-pause',
    'phone-slash',
    'phone-x',
    // More platforms
    'linktree-logo',
    'amazon-logo',
    'apple-logo',
    'google-logo',
    'microsoft-teams-logo',
    'open-ai-logo',
    'meta-logo',
    'read-cv-logo',
    // More people
    'users',
    'users-three',
    'users-four',
    // Fire & energy
    'fire',
    'fire-simple',
    'lightning',
    'sparkle',
    // Broken heart + pulse
    'heartbeat',
    'pulse',
    // Celebration
    'crown',
    'crown-simple',
    'trophy',
    'medal',
    'certificate',
    // Image broken
    'image-broken',
    // Location & discovery
    'globe',
    'globe-hemisphere-east',
    'globe-hemisphere-west',
    'globe-simple',
    'map-pin',
    'compass',
    'star-and-crescent',
  ],

  signs: [
    // Warnings & alerts
    'warning',
    'warning-circle',
    'warning-diamond',
    'warning-octagon',
    'prohibit',
    'prohibit-inset',
    'info',
    'question',
    'exclamation-mark',
    'asterisk',
    'asterisk-simple',
    // Confirmation
    'check',
    'check-circle',
    'check-fat',
    'check-square',
    'check-square-offset',
    'checks',
    // Cancellation
    'x',
    'x-circle',
    'x-square',
    // Add / Remove
    'minus',
    'minus-circle',
    'minus-square',
    'plus',
    'plus-circle',
    'plus-square',
    // Stop / Pause
    'stop',
    'stop-circle',
    // Fire & emergency
    'fire',
    'fire-extinguisher',
    'fire-simple',
    'ambulance',
    'lifebuoy',
    'first-aid',
    'traffic-cone',
    // Flags
    'flag',
    'flag-banner',
    'flag-checkered',
    'flag-pennant',
    'flag-banner-fold',
    // Recycling & environment
    'recycle',
    // Electrical & radiation
    'lightning',
    'lightning-slash',
    'radioactive',
    // Skull & danger
    'skull',
    // Navigation & directions
    'arrow-circle-down',
    'arrow-circle-up',
    'arrow-circle-left',
    'arrow-circle-right',
    'arrow-circle-up-left',
    'arrow-circle-up-right',
    'arrow-circle-down-left',
    'arrow-circle-down-right',
    'arrow-fat-up',
    'arrow-fat-down',
    'arrow-fat-left',
    'arrow-fat-right',
    'arrow-fat-line-up',
    'arrow-fat-line-down',
    'arrow-up',
    'arrow-down',
    'arrow-left',
    'arrow-right',
    'arrows-clockwise',
    'arrows-counter-clockwise',
    'arrows-in',
    'arrows-out',
    'arrows-merge',
    'arrows-split',
    'arrows-horizontal',
    'arrows-vertical',
    'arrows-down-up',
    // Chevrons
    'caret-up',
    'caret-down',
    'caret-left',
    'caret-right',
    'caret-circle-up',
    'caret-circle-down',
    // Entry / Exit
    'sign-in',
    'sign-out',
    'signpost',
    'road-horizon',
    // Shapes as indicators
    'circle',
    'circle-dashed',
    // Crosshair / targeting
    'crosshair',
    // Math symbols used as signs
    'percent',
    'equals',
    'divide',
    'approximate-equals',
    // Numbered circles (ordinal signs)
    'number-circle-zero',
    'number-circle-one',
    'number-circle-two',
    'number-circle-three',
    'number-circle-four',
    'number-circle-five',
    'number-circle-six',
    'number-circle-seven',
    'number-circle-eight',
    'number-circle-nine',
    // Numbered squares
    'number-square-zero',
    'number-square-one',
    'number-square-two',
    'number-square-three',
    'number-square-four',
    'number-square-five',
    'number-square-six',
    'number-square-seven',
    'number-square-eight',
    'number-square-nine',
    // Dots & bullet indicators
    'dot',
    'dot-outline',
    'dots-three',
    'dots-six',
    'dots-nine',
    'dots-three-circle',
    'dots-three-outline',
    'dots-three-vertical',
    'dots-six-vertical',
    // Curved & bent arrows
    'arrow-arc-left',
    'arrow-arc-right',
    'arrow-bend-up-left',
    'arrow-bend-up-right',
    'arrow-bend-down-left',
    'arrow-bend-down-right',
    'arrow-counter-clockwise',
    'arrow-clockwise',
    // Line arrows
    'arrow-line-up',
    'arrow-line-down',
    'arrow-line-left',
    'arrow-line-right',
    // Square arrows
    'arrow-square-up',
    'arrow-square-down',
    'arrow-square-in',
    'arrow-square-out',
    // Diagonal arrows
    'arrow-up-left',
    'arrow-up-right',
    'arrow-down-left',
    'arrow-down-right',
    // Double carets
    'caret-circle-left',
    'caret-circle-right',
    'caret-double-up',
    'caret-double-down',
    'caret-line-up',
    'caret-line-down',
  ],

  calendar: [
    // Calendar variants
    'calendar',
    'calendar-blank',
    'calendar-check',
    'calendar-dot',
    'calendar-dots',
    'calendar-heart',
    'calendar-minus',
    'calendar-plus',
    'calendar-slash',
    'calendar-star',
    'calendar-x',
    // Clock variants
    'clock',
    'clock-afternoon',
    'clock-clockwise',
    'clock-countdown',
    'clock-counter-clockwise',
    'clock-user',
    // Timers & watch
    'timer',
    'watch',
    // Hourglass
    'hourglass',
    'hourglass-high',
    'hourglass-low',
    'hourglass-medium',
    'hourglass-simple',
    'hourglass-simple-high',
    'hourglass-simple-low',
    'hourglass-simple-medium',
    // Alarms & bells
    'alarm',
    'bell',
    'bell-simple',
    'bell-ringing',
    'bell-simple-ringing',
    'bell-slash',
    'bell-simple-slash',
    'bell-z',
    'bell-simple-z',
    'notification',
    // Sun, moon & celestial
    'sun',
    'sun-dim',
    'sun-horizon',
    'moon',
    'moon-stars',
    'star-four',
    'star-and-crescent',
    'star-of-david',
    'shooting-star',
    'planet',
    'meteor',
    // Weather & seasons
    'cloud-sun',
    'cloud-moon',
    'cloud-rain',
    'cloud-snow',
    'cloud-lightning',
    'cloud-fog',
    'snowflake',
    'wind',
    'rainbow',
    'rainbow-cloud',
    'hurricane',
    'lightning',
    'tornado',
    // Nature (seasonal indicators)
    'leaf',
    'flower',
    'flower-lotus',
    'flower-tulip',
    'tree',
    'tree-palm',
    'tree-evergreen',
    'drop',
    'drop-half',
    'drop-simple',
    'drop-slash',
    'waves',
    // Repeat & cycles
    'repeat',
    'repeat-once',
    'arrows-clockwise',
    'arrows-counter-clockwise',
    'fast-forward',
    'fast-forward-circle',
    'rewind',
    'infinity',
    'recycle',
    // Progress & steps
    'steps',
    // Lists / agenda-like
    'queue',
    // Playback controls (time-control metaphors)
    'pause',
    'pause-circle',
    'play',
    'play-circle',
    'stop',
    'stop-circle',
    'record',
    'flag-checkered',
    // More lightning & signals
    'lightning-a',
    'lightning-slash',
    // Media with time dimension
    'music-note',
    'music-notes',
    'music-notes-plus',
    'music-notes-simple',
    'playlist',
    // Log & history
    'log',
  ],
};

export function getAllIconNames() {
  return Array.from(new Set(Object.values(CATEGORIES).flat()));
}

export function getIconNamesForCategory(category) {
  return CATEGORIES[category] ?? [];
}

export const CATEGORY_NAMES = Object.keys(CATEGORIES);
